[package]
name = "provider-storage"
version.workspace = true
edition.workspace = true
publish.workspace = true

[features]
test-util = []

[dependencies]
async-trait.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
provider-auth.workspace = true
provider-core.workspace = true
provider-usage.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sqlx.workspace = true
thiserror.workspace = true

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
